Algoritmo "Calculando_media"

// Data atual  : 28/02/2022
Var
// Seção de Declarações das variáveis 
   n1, n2, soma: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva("Digite a nota1: ")
   leia(n1)
   escreva("Digite a Nota2:" )
   leia(n2)

   
   soma <- n1 + n2
   escreva("Sua primeira Nota" , n1)
   escreva("Sua segunda nota" , n2)

   escreva("Sua media ",soma)
   


Fimalgoritmo